import '../styles/globals.css';
import { Inter } from 'next/font/google';
import { motion, AnimatePresence } from 'framer-motion';

import styles from '../styles';
import { navVariants } from '../utils/motion';
import { MaterialUISwitch } from '../utils/swith-dark-mode';
import { useState } from 'react';
import CloseOutlinedIcon from '@mui/icons-material/CloseOutlined';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Portofolio Faisal Saleh',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head></head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
